const cardsArray = [
    { item: '1',
        isActive: true,
        isRotate: false },
    { item: '2',
        isActive: true,
        isRotate: false },
    { item: '3',
        isActive: true,
        isRotate: false },
    { item: '4',
        isActive: true,
        isRotate: false },
    { item: '5',
        isActive: true,
        isRotate: false },
    { item: '6',
        isActive: true,
        isRotate: false },
    { item: '7',
        isActive: true,
        isRotate: false },
    { item: '8',
        isActive: true,
        isRotate: false },
    { item: '9',
        isActive: true,
        isRotate: false },
    { item: '10',
        isActive: true,
        isRotate: false },
    { item: '11',
        isActive: true,
        isRotate: false },
    { item: '12',
        isActive: true,
        isRotate: false },
    { item: '13',
        isActive: true,
        isRotate: false },
    { item: '14',
        isActive: true,
        isRotate: false },
    { item: '15',
        isActive: true,
        isRotate: false },
    { item: '16',
        isActive: true,
        isRotate: false },
    { item: '17',
        isActive: true,
        isRotate: false },
    { item: '18',
        isActive: true,
        isRotate: false }
];

export default cardsArray;
